[project]
name = "mapigen"
version = "1.0.0"
description = "API Contract registry engine compiling and bundling for the MAPI ecosystem"
authors = [
    {name = "Evan Huang",email = "meoya.dev@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "msgspec (>=0.19.0,<0.20.0)",
    "zstandard (>=0.25.0,<0.26.0)",
    "niquests (>=3.15.2,<4.0.0)",
    "structlog (>=25.5.0,<26.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
black = "^25.9.0"
isort = "^7.0.0"
mypy = "^1.18.2"
pytest = "^8.4.2"

