"""
Auto-generated functional integration tests for the spotify/RESTAPI service.

This file was generated by the `utils/generate_integration_tests.py` script.
It dynamically discovers operations and generates test cases with sampled
parameters to verify that the client can communicate with the endpoints.
"""
import pytest
from dotenv import load_dotenv
from typing import Any, List, Dict, Tuple

from mapigen import Mapi
from ..reporting import run_test_operation

load_dotenv()

PROVIDER_NAME = "spotify"
API_NAME = "RESTAPI"

# A list of test cases, where each case is a tuple of:
# (operation_name, test_case_name, parameters_dict)
TEST_CASES: List[Tuple[str, str, Dict[str, Any]]] = [
("add-to-queue", "add-to-queue", {'uri': 'test_uri', 'device_id': 'test_device_id'}),
("get-a-shows-episodes", "get-a-shows-episodes", {'id': 'test_id', 'market': 'test_market', 'limit': 20, 'offset': 0}),
("get-featured-playlists", "get-featured-playlists", {'locale': 'test_locale', 'limit': 20, 'offset': 0}),
("get-recommendations", "get-recommendations", {'limit': 20, 'market': 'test_market', 'seed_artists': 'test_seed_artists', 'seed_genres': 'test_seed_genres', 'seed_tracks': 'test_seed_tracks', 'min_acousticness': 1.1, 'max_acousticness': 1.1, 'target_acousticness': 1.1, 'min_danceability': 1.1, 'max_danceability': 1.1, 'target_danceability': 1.1, 'min_duration_ms': 1, 'max_duration_ms': 1, 'target_duration_ms': 1, 'min_energy': 1.1, 'max_energy': 1.1, 'target_energy': 1.1, 'min_instrumentalness': 1.1, 'max_instrumentalness': 1.1, 'target_instrumentalness': 1.1, 'min_key': 1, 'max_key': 1, 'target_key': 1, 'min_liveness': 1.1, 'max_liveness': 1.1, 'target_liveness': 1.1, 'min_loudness': 1.1, 'max_loudness': 1.1, 'target_loudness': 1.1, 'min_mode': 1, 'max_mode': 1, 'target_mode': 1, 'min_popularity': 1, 'max_popularity': 1, 'target_popularity': 1, 'min_speechiness': 1.1, 'max_speechiness': 1.1, 'target_speechiness': 1.1, 'min_tempo': 1.1, 'max_tempo': 1.1, 'target_tempo': 1.1, 'min_time_signature': 1, 'max_time_signature': 1, 'target_time_signature': 1, 'min_valence': 1.1, 'max_valence': 1.1, 'target_valence': 1.1}),
("skip-users-playback-to-previous-track", "skip-users-playback-to-previous-track", {'device_id': 'test_device_id'}),
]

@pytest.fixture(scope="module")
def client() -> Mapi:
    """
    Pytest fixture to initialize the Mapi client for the RESTAPI service.
    This fixture is a placeholder and may need to be updated with authentication
    details for the service.
    """
    # TODO: Add authentication logic if required by the service.
    return Mapi()

@pytest.mark.parametrize("op_name, case_name, params", TEST_CASES)
def test_sampled_operation(client: Mapi, op_name: str, case_name: str, params: Dict[str, Any]):
    """
    Dynamically tests an operation with a sampled set of parameters.
    The test case name (e.g., 'min_params') is included for clarity.
    """
    operations_checked: List[str] = []

    def generic_assertion(data: Any):
        """A generic assertion that passes as long as the call completes."""
        assert data is not None

    run_test_operation(
        client=client,
        provider_name=PROVIDER_NAME,
        api_name=API_NAME,
        op_name=op_name,
        operations_checked=operations_checked,
        assertion_callback=generic_assertion,
        **params
    )