"""
Auto-generated functional integration tests for the stripe/stripe service.

This file was generated by the `utils/generate_integration_tests.py` script.
It dynamically discovers operations and generates test cases with sampled
parameters to verify that the client can communicate with the endpoints.
"""
import pytest
from dotenv import load_dotenv
from typing import Any, List, Dict, Tuple

from mapigen import Mapi
from ..reporting import run_test_operation

load_dotenv()

PROVIDER_NAME = "stripe"
API_NAME = "stripe"

# A list of test cases, where each case is a tuple of:
# (operation_name, test_case_name, parameters_dict)
TEST_CASES: List[Tuple[str, str, Dict[str, Any]]] = [
("GetAccount", "GetAccount", {'expand': []}),
("GetIssuingTokensToken", "GetIssuingTokensToken", {'token': 'test_token', 'expand': []}),
("PostAccountsAccountPersonsPerson", "PostAccountsAccountPersonsPerson", {'account': 'test_account', 'person': 'test_person', 'additional_tos_acceptances': 'unknown_type', 'address': 'unknown_type', 'address_kana': 'unknown_type', 'address_kanji': 'unknown_type', 'dob': 'unknown_type', 'documents': 'unknown_type', 'email': 'unknown_type', 'expand': 'unknown_type', 'first_name': 'unknown_type', 'first_name_kana': 'unknown_type', 'first_name_kanji': 'unknown_type', 'full_name_aliases': 'unknown_type', 'gender': 'unknown_type', 'id_number': 'unknown_type', 'id_number_secondary': 'unknown_type', 'last_name': 'unknown_type', 'last_name_kana': 'unknown_type', 'last_name_kanji': 'unknown_type', 'maiden_name': 'unknown_type', 'metadata': 'unknown_type', 'nationality': 'unknown_type', 'person_token': 'unknown_type', 'phone': 'unknown_type', 'political_exposure': 'unknown_type', 'registered_address': 'unknown_type', 'relationship': 'unknown_type', 'ssn_last_4': 'unknown_type', 'us_cfpb_data': 'unknown_type', 'verification': 'unknown_type'}),
("PostPaymentMethodsPaymentMethodDetach", "PostPaymentMethodsPaymentMethodDetach", {'payment_method': 'test_payment_method', 'expand': 'unknown_type'}),
("PostWebhookEndpointsWebhookEndpoint", "PostWebhookEndpointsWebhookEndpoint", {'webhook_endpoint': 'test_webhook_endpoint', 'description': 'unknown_type', 'disabled': 'unknown_type', 'enabled_events': 'unknown_type', 'expand': 'unknown_type', 'metadata': 'unknown_type', 'url': 'unknown_type'}),
]

@pytest.fixture(scope="module")
def client() -> Mapi:
    """
    Pytest fixture to initialize the Mapi client for the stripe service.
    This fixture is a placeholder and may need to be updated with authentication
    details for the service.
    """
    # TODO: Add authentication logic if required by the service.
    return Mapi()

@pytest.mark.parametrize("op_name, case_name, params", TEST_CASES)
def test_sampled_operation(client: Mapi, op_name: str, case_name: str, params: Dict[str, Any]):
    """
    Dynamically tests an operation with a sampled set of parameters.
    The test case name (e.g., 'min_params') is included for clarity.
    """
    operations_checked: List[str] = []

    def generic_assertion(data: Any):
        """A generic assertion that passes as long as the call completes."""
        assert data is not None

    run_test_operation(
        client=client,
        provider_name=PROVIDER_NAME,
        api_name=API_NAME,
        op_name=op_name,
        operations_checked=operations_checked,
        assertion_callback=generic_assertion,
        **params
    )